Dsegog 369 migrate to python 3.11
ral-facilities/operationsgateway-api pull request #147
Opened 2024-11-27 10:13 UTC by moonraker595

The dev server currently uses Rocky 8 with the API running Python 3.8.

Migrating the dev server to Rocky 9 means updating to Python 3.9 as it doesn’t come with 3.8.

We might as well migrate the code base and associated setup to Python 3.11 to save doing it later.

This PR makes the necessary code changes to get the API running, and tested on 3.11.

The main issue has been getting the tests to run given a newer version of `matplotlib`, which includes some aliases. These have been excluded from the test as they are the same as existing ones.

2024-11-28 09:15 UTC, kevinphippsstfc requested changes
Just doing a search for 3.8 across the repo I found that there is a reference to 3.8, 3.9, 3.10 in the docs/github_actions.md file so that paragraph could do with updating as we do not have that complication any more.

2024-11-28 10:05 UTC, moonraker595 commented on README.md
>  To install the project's dependencies, execute `poetry install`. The dependencies and the code in this repo are compatible with Python >=3.8, <3.12.
Thanks for that, these changes have been made

2025-01-16 14:06 UTC, kevinphippsstfc requested changes

2025-01-16 14:06 UTC, kevinphippsstfc commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-22.04
As Louise commented, ubuntu 24.04 is available so lets try moving forward to that whilst we are updating this.

2025-01-28 09:39 UTC, moonraker595 commented
Hi, I appreciate the heads-up on this. I encountered this late last night and didn’t realise this was the issue.


From: patrick-austin ***@***.***>
Date: Monday, 27 January 2025 at 17:04
To: ral-facilities/operationsgateway-api ***@***.***>
Cc: Kemp, Alexander (STFC,RAL,SC) ***@***.***>, Author ***@***.***>
Subject: Re: [ral-facilities/operationsgateway-api] Dsegog 369 migrate to python 3.11 (PR #147)

@patrick-austin commented on this pull request.

________________________________

In pyproject.toml<https://github.com/ral-facilities/operationsgateway-api/pull/147#discussion_r1930872547>:

> @@ -26,7 +26,7 @@ matplotlib = "^3.5.2"

 gunicorn = "^23.0.0"

 orjson = "^3.10.3"

 python-dateutil = "^2.8.2"

-PyJWT = "2.4.0"

+PyJWT = "2.10.1"

 cryptography = "^43.0.1"

 python-ldap = "3.4.2"

 boto3 = "^1.26.97"
⬇️ Suggested change

-boto3 = "^1.26.97"

+boto3 = ">=1.26.97,<1.36.0"

FYI, I ran into this<https://github.com/boto/boto3/issues/4398> both in this repo and in the FDP work. I think it might be because we're using the CephOS interface, which isn't strictly S3? Regardless of the reason, I can't run ingest locally with v1.36 (which I still had installed from starting on #152<https://github.com/ral-facilities/operationsgateway-api/pull/152> ):

$ python ../util/ingest_hdf.py --username backend --password back --path v1.1

Checking if API started

API not started yet...

API not started yet...

API not started yet...

API not started yet...

API started on http://127.0.0.1:8000

Login as 'backend' to get access token

Ingested channel manifest file, ID: 20250127154737

Iterating through v1.1/h5

500 returned

('{"detail":"MissingContentLength when uploading file at '

 '\'waveforms/20230606120000/CM-202-CVC-SP.json\'"}')

Ingestion of v1.1/h5 complete, time taken: 1.39 seconds

API stopped on http://127.0.0.1:8000



$ pip list | grep boto3

boto3                 1.36.6



$ poetry install

Installing dependencies from lock file



Package operations: 0 installs, 18 updates, 0 removals



  - Downgrading botocore (1.36.6 -> 1.35.67)

[...]



$ python ../util/ingest_hdf.py --username backend --password back --path v1.1

Checking if API started

API not started yet...

API not started yet...

API not started yet...

API not started yet...

API started on http://127.0.0.1:8000

Login as 'backend' to get access token

Ingested channel manifest file, ID: 20250127155434

Iterating through v1.1/h5

Ingested 2023-06-06T1200.h5, time taken: 7.31 seconds

Ingestion of v1.1/h5 complete, time taken: 7.31 seconds

API stopped on http://127.0.0.1:8000

Since this change would upgrade us to 1.36.2 (see poetry.lock) I think it would be good to pin the version of boto3 to avoid introducing that failure.

—
Reply to this email directly, view it on GitHub<https://github.com/ral-facilities/operationsgateway-api/pull/147#pullrequestreview-2576022790>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AFS6J3JFBX72HEEUUCWYHIT2MZRJLAVCNFSM6AAAAABSSOXBSGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNZWGAZDENZZGA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-02-03 10:23 UTC, patrick-austin approved these changes
Have only reviewed the changes since Kevin's last review (https://github.com/ral-facilities/operationsgateway-api/pull/147/commits/24e06514b658874d4fdb045339113d58b93796fb onward) and these look fine and address the comments so approving.

2025-02-03 13:55 UTC, kevinphippsstfc approved these changes

2025-02-03 13:56 UTC, merged