Dsegog 271 handling failed ingestion
ral-facilities/operationsgateway-api pull request #148
Opened 2024-11-28 08:50 UTC by moonraker595

This PR addresses the cases where “network blips” may occur, impacting the ingestion process. It mainly focuses on the following issues:
1)	Failures that happen before ingestion, meaning that there are network issues where the API is still accessible, but the DB and ECHO are not BEFORE the ingestion process starts.
2)	Failures that happen mid-way through ingestion of a NEW hdf, meaning that some data has already been ingested before network issues render either or both the DB and ECHO stores unavailable.
3)	Failures that happen mid-way through ingestion of a UPDATED hdf, meaning that some data has already been ingested before network issues render either or both the DB and ECHO stores unavailable.
Each one of these can have 3 different failure states, where either/or the database and echo can’t be contacted:

•	The DB and ECHO are not accessible 
•	The DB is but ECHO is not accessible 
•	The DB is not but ECHO is accessible 

To help with the manual debugging of this task, an application was created to generate and send newly created hdf files. Here: https://github.com/ral-facilities/operationsgateway-hdf5-generator
 
From this, the state table below can be constructed. 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<body lang=EN-GB style='tab-interval:36.0pt;word-wrap:break-word'>

No | State | Mitigation | Response | Tested?
-- | -- | -- | -- | --
1.1 | The DB and ECHO are not accessible before ingestion starts. | The API is unable to authenticate the user. The API   fails the request as part of its pre-flight checks, so the request is thrown   out before any “code” in the endpoint is hit. | 500 | Manual debuging
1.2 | The DB is but ECHO is   not accessible before ingestion starts. | Any channels that require echo such as waveforms and   images are added to the list of failed channels. The failed channels are not   added to the DB. The upload to ECHO happens before the DB insertions so there   is nothing to roll back. Other channels are processed and the metadata for   the file is updated in the DB. | 201 | test_echo_   failure_on_start
1.3 | The DB is not but ECHO is   accessible before ingestion starts. | The API is unable to authenticate the user, same   outcome as 1.1 | 500 | Manual debuging
  |   |   |   |  
2.1 | DB and   ECHO become inaccessible mid-way through   ingesting a NEW .h5 file. | If both become unavailable when some channels have   already been updated and the user has already been authenticated then the   first thing to fail will be ECHO and the channels will be removed from the   record, next the DB insertion will fail and a 500 will be returned along with   “Database error” | 500 | test_partial_s3_   and_db_upload_failure
2.2 | The DB is but ECHO is   not accessible mid-way through ingesting a NEW .h5 file. | Same outcome as a 1.2 | 201 | test_partial_   s3_upload_failure
2.3 | The DB is not but ECHO is   accessible mid-way through ingesting a NEW .h5 file. | Files will be updated to ECHO but not the db, 500   will be returned along with “Database error”. THIS WILL MEAN DANGLING DATA   IN ECHO. This is difficult to test, the only way of forcing an error   mid-way through ingestion is through the unit tests, which clear up all tests   file after. | 500 | test_partial_db_failure
  |   |   |   |  
3.1 | DB and   ECHO become inaccessible mid-way through   ingesting a UPDATED .h5 file. | Same outcome as a 2.1 | 500 | Manual debuging
3.2 | The DB is but ECHO is   not accessible mid-way through ingesting a UPDATED .h5 file. | Same outcome as a 1.2 | 201 | Manual debuging
3.3 | The DB is not but ECHO is   accessible mid-way through ingesting a UPDATED .h5 file. | Same outcome as a 2.3 | 500 | Manual debuging

</body>

</html>

2025-01-16 14:54 UTC, kevinphippsstfc approved these changes

2025-01-20 13:35 UTC, moonraker595 commented
This PR addresses the cases where “network blips” may occur, impacting the ingestion process. It mainly focuses on the following issues:
1)	Failures that happen before ingestion, meaning that there are network issues where the API is still accessible, but the DB and ECHO are not BEFORE the ingestion process starts.
2)	Failures that happen mid-way through ingestion of a NEW hdf, meaning that some data has already been ingested before network issues render either or both the DB and ECHO stores unavailable.
3)	Failures that happen mid-way through ingestion of a UPDATED hdf, meaning that some data has already been ingested before network issues render either or both the DB and ECHO stores unavailable.
Each one of these can have 3 different failure states, where either/or the database and echo can’t be contacted:

•	The DB and ECHO are not accessible 
•	The DB is but ECHO is not accessible 
•	The DB is not but ECHO is accessible 

To help with the manual debugging of this task, an application was created to generate and send newly created hdf files. Here: https://github.com/ral-facilities/operationsgateway-hdf5-generator
 
From this, the state table below can be constructed. 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">



<body lang=EN-GB style='tab-interval:36.0pt;word-wrap:break-word'>
<!--StartFragment-->


No | State | Mitigation | Response | Tested?
-- | -- | -- | -- | --
1.1 | The DB and ECHO are not accessible before ingestion starts. | The API is unable to authenticate the user. The API   fails the request as part of its pre-flight checks, so the request is thrown   out before any “code” in the endpoint is hit. | 500 | Manual debuging
1.2 | The DB is but ECHO is   not accessible before ingestion starts. | Any channels that require echo such as waveforms and   images are added to the list of failed channels. The failed channels are not   added to the DB. The upload to ECHO happens before the DB insertions so there   is nothing to roll back. Other channels are processed and the metadata for   the file is updated in the DB. | 201 | test_echo_   failure_on_start
1.3 | The DB is not but ECHO is   accessible before ingestion starts. | The API is unable to authenticate the user, same   outcome as 1.1 | 500 | Manual debuging
  |   |   |   |  
2.1 | DB and   ECHO become inaccessible mid-way through   ingesting a NEW .h5 file. | If both become unavailable when some channels have   already been updated and the user has already been authenticated then the   first thing to fail will be ECHO and the channels will be removed from the   record, next the DB insertion will fail and a 500 will be returned along with   “Database error” | 500 | test_partial_s3_   and_db_upload_failure
2.2 | The DB is but ECHO is   not accessible mid-way through ingesting a NEW .h5 file. | Same outcome as a 1.2 | 201 | test_partial_   s3_upload_failure
2.3 | The DB is not but ECHO is   accessible mid-way through ingesting a NEW .h5 file. | Files will be updated to ECHO but not the db, 500   will be returned along with “Database error”. THIS WILL MEAN DANGLING DATA   IN ECHO. This is difficult to test, the only way of forcing an error   mid-way through ingestion is through the unit tests, which clear up all tests   file after. | 500 | test_partial_db_failure
  |   |   |   |  
3.1 | DB and   ECHO become inaccessible mid-way through   ingesting a UPDATED .h5 file. | Same outcome as a 2.1 | 500 | Manual debuging
3.2 | The DB is but ECHO is   not accessible mid-way through ingesting a UPDATED .h5 file. | Same outcome as a 1.2 | 201 | Manual debuging
3.3 | The DB is not but ECHO is   accessible mid-way through ingesting a UPDATED .h5 file. | Same outcome as a 2.3 | 500 | Manual debuging



<!--EndFragment-->
</body>

</html>

2025-01-29 17:24 UTC, patrick-austin requested changes
EDIT: I almost forgot to mention, I've only looked at the changes from https://github.com/ral-facilities/operationsgateway-api/pull/148/commits/6a190a35bb51eac6f16cf097b72cbd2faf4f7292 onwards - I had a look at the git graph, and the ones before that also appear in the branch for #147 . So I figured they would be covered and reviewed by that PR. If you want I can review them as part of this one as well, just let me know.

Looks good on the whole, especially the in-depth testing with the extensive use of side effects on the patched functions.

I had a few queries in the in line comments, but most are minor - the only one I feel (somewhat) strongly about is that we should be calling `log.error` in `mongo_error_handling.py` like we do elsewhere.

In terms of coverage I mentioned one of the places, the other two seem like either defensive programming (the `remove_channel` `else` block) or otherwise would be difficult to reach (having multiple failure reasons for a single channel - setting up the mocks to get one failure seems like enough of an ask), so I think it's OK to leave these uncovered if you're happy to.

2025-01-29 17:24 UTC, patrick-austin commented on test/mongo/test_mongo_error_handling.py
> +    async def test_find_one_exception_in_interface(
It's not major since the code is almost identical, but it looks like there's only a test for the async version of the error handling (and the code cov is identifying it as two of the missing lines of coverage). We could add a test for the synchronous version as well.

2025-01-30 13:30 UTC, moonraker595 commented on operationsgateway_api/src/mongo/interface.py
> +    @mongodb_error_handling("find")
The comment 

> the query is executed in query_to_list()

 doesn't make much sense as there is no clear link between the `find` and `query_to_list()` functions.
 
 Nevertheless, i've added the suggested change and left the comment in, hoping it may one day be useful.

2025-01-30 15:01 UTC, moonraker595 commented on operationsgateway_api/src/mongo/mongo_error_handling.py
> +                    ) from exc
> Only except classes that aren't our custom DatabaseError class. This way we get a more bespoke error message, and a shorter stack, whilst still raising our custom type.

In general, I think obscuring the error handling through abstraction (in this case; function decorators) isn't a great idea, but I'm sticking with convension.

I think I understand what you are getting at, having both the code and the decorator returning `DataBaseError` seem pretty redundant.

### Example: looking at `update_many`:
```
@staticmethod
    @mongodb_error_handling("update_many")
    async def update_many(
        collection_name: str,
        filter_: Dict[str, Any] = {},  # noqa: B006
        update: Dict[str, Any] = {},  # noqa: B006
        upsert: bool = False,
    ):
        log.info("Sending update_many() to MongoDB, collection: %s", collection_name)
        log.debug("Filter: %s", filter_)

        collection = MongoDBInterface.get_collection_object(collection_name)

        try:
            return await collection.update_many(
                filter_,
                update,
                upsert=upsert,
            )
        except WriteError as exc:
            raise DatabaseError(
                "Error when updating multiple documents in %s collection",
                collection_name,
            ) from exc
```

- If a WriteError occurs, it gets caught by the `mongodb_error_handling` decorator, which wraps it in a `DatabaseError`.
- By the time the execution returns to `update_many`, the error is now a `DatabaseError`, not a `WriteError` anymore.
- That means that the code: `except WriteError as exc:`  is never run because WriteError is now inside a DatabaseError, this except block no longer matches.

From there, I think the best thing to do is remove the try/catch blocks from `interface.py`, letting the decorator do the work and beef up the reporting in the decorator. 

For example; as it is...

```
log.error("Database operation failed during: %s", operation)
raise DatabaseError(
    f"Database operation failed during {operation}",
) from exc
```

would return "Database operation failed during: update_many" which doesn't give us much clue as to what went on. 

So I think we should beef up the reporting in the decorator to something like:

```
def mongodb_error_handling(operation):
    """
    Decorator for handling MongoDB errors in database operations.
    """
    def decorator(method):
        @wraps(method)
        async def wrapper(*args, **kwargs):
            try:
                return await method(*args, **kwargs)
            except Exception as exc:
                log.error(
                    "MongoDB error in %s(): %s\nArgs: %s\nKwargs: %s",
                    method.__name__, exc, args, kwargs,
                )
                raise DatabaseError(
                    f"Database operation failed during '{operation}'. "
                    f"Original error: {exc}"
                ) from exc

        return wrapper
    return decorator
```

This gives us a cleaner codebase in `interface.py`, so we haven't got try/catches everywhere and gives us the details of the original Mongo error.

Although I haven't tested this, from what I understand the raised error would still propagate up the chain, that is, you don't have to catch it in `update_many` and re-raise it.

Hopefully this makes sense, let me know what you think.

2025-01-30 16:30 UTC, moonraker595 commented on operationsgateway_api/src/records/record.py
> +            log.warning("Channel '%s' not found in record.", channel_name)
Agreed, Upon reflection, I don't think there's a need to handle any errors here. Records are internal anyway so not touching any db or echo stuff here. If the failed upload isn't in the record then there was an error putting it in the first place. 

I'll remove the KeyError but keep the bit that checks the channel is in the record for good measure.

2025-01-31 10:26 UTC, patrick-austin commented on operationsgateway_api/src/mongo/mongo_error_handling.py
> +                    ) from exc
Yeah I agree that in having the error handling in one place is probably better, regardless of which place it's in. I think the proposed solution of increasing the amount of information in the wrapper is good, and will ensure that the final message lets us distinguishes between "expectable" errors (like a write operation failed to write) and "un-expectable" errors (like a dropped connection).

### Going on a tangent:

I think the main advantage of the wrapper is it will catch all Errors (such as dropped connections) not just the ones we expect (like `WriteError`) and let us give them a custom status code etc. by use of our own exception classes (I actually think Matt gave a talk about this reasoning ages ago, when Alejandra and Fan were organising knowledge sharing meetings between our groups). That being said I don't know if I would do it if starting from scratch, and it definitely introduces more complexity...

My understanding of the order of the errors is slightly different, I think we will execute `except WriteError as exc` because the decorator applies to `MongoDBInterface.update_many` rather than `collection.update_many`. `WriteError` will be caught, re-raised as `DatabaseError` within `MongoDBInterface.update_many`; then caught again by the wrapper and re-raised as a second `DatabaseError`. I tried a toy example to check this:

```python
from functools import wraps


def error_handler():
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            try:
                return func(*args, **kwargs)
            except Exception as exc:
                raise RuntimeError("Caught by the wrapper") from exc

        return wrapper

    return decorator

@error_handler()
def raise_runtime():
    try:
        raise ValueError("Original exception")
    except ValueError as exc:
        raise RuntimeError("Caught by function with detailed info") from exc
    
raise_runtime()
```

Which gives:

```
$ python tmp.py 
Traceback (most recent call last):
  File "/home/kez92691/operationsgateway-api/tmp.py", line 20, in raise_runtime
    raise ValueError("Original exception")
ValueError: Original exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kez92691/operationsgateway-api/tmp.py", line 9, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kez92691/operationsgateway-api/tmp.py", line 22, in raise_runtime
    raise RuntimeError("Caught by function with detailed info") from exc
RuntimeError: Caught by function with detailed info

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kez92691/operationsgateway-api/tmp.py", line 24, in <module>
    raise_runtime()
  File "/home/kez92691/operationsgateway-api/tmp.py", line 11, in wrapper
    raise RuntimeError("Caught by the wrapper") from exc
RuntimeError: Caught by the wrapper
```

So we hit both, but the final message is the one from the decorator (which will ultimately get set on the HTTP error we return, and the traceback is lost).

2025-01-31 12:40 UTC, moonraker595 commented on operationsgateway_api/src/mongo/mongo_error_handling.py
> +                    ) from exc
Thanks for that. In hindsight, a test script would've been a good idea and I'll consider this going forward. As it is, trying to test a brake in db connection, sometimes partway through an ingest is harder than teaching a goldfish to fetch. I think I'll stick with what's there rather than trying to refactor the whole thing.

So going back to your original PR comment. Did you have something like this in mind?
```
def mongodb_error_handling(operation):
    def decorator(func):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            try:
                return await func(*args, **kwargs)
            except DatabaseError:
                raise  # If it's already a DatabaseError, propagate it as-is
            except Exception as exc:
                log.error(f"Database operation '{operation}' failed: {exc}")
                raise DatabaseError(f"Database operation failed during: {operation}") from exc
        return wrapper
    return decorator
 ```

2025-01-31 13:43 UTC, patrick-austin commented on operationsgateway_api/src/mongo/mongo_error_handling.py
> +                    ) from exc
Yeah I agree that trying to actually test error handling for this sort of thing is challenging, and the effort required in triggering it is potentially not worth it. I think it makes sense to not significantly refactor if it would end up being too much work - I wouldn't want this to end up eating up too much time.

Yes that's what I was originally thinking of, though I couldn't quite remember the syntax for multiple except clauses in Python so tried to describe it with words (looking it up and posting a snippet would probably have been helpful, apologies).

2025-01-31 16:37 UTC, moonraker595 commented on operationsgateway_api/src/mongo/mongo_error_handling.py
> +                    ) from exc
No Problem, we got there in the end and I've learned a bit more about error handling.

This is done in commit: https://github.com/ral-facilities/operationsgateway-api/commit/b65af8e3bec1885c621b81731ca0bd806f9f47bb

2025-02-03 09:28 UTC, moonraker595 commented on operationsgateway_api/src/mongo/mongo_error_handling.py
> +                    ) from exc
handled above

2025-02-03 12:06 UTC, moonraker595 commented on test/mongo/test_mongo_error_handling.py
> +    async def test_find_one_exception_in_interface(
Thanks for this, I hadn't really given much thought to the code cov. 
As of commit abfe6fdd26adf6141c1337e787a0661b33a92063 coverage is at 100% for this file.

2025-02-03 13:05 UTC, patrick-austin approved these changes

2025-02-04 11:07 UTC, merged