DSEGOG-256 user preferences
ral-facilities/operationsgateway-api pull request #71
Opened 2023-08-23 14:47 UTC by kevinphippsstfc

This PR adds the functionality to get, set and delete preferences on a per user basis. Preferences of type string, int, float and bool can be set.

This functionality is currently required to enable each user to specify their preferred colour map which will be applied to any images returned from the API. It is likely that other user preferences will also need to be set so the functionality is generic to allow for this. The preferences are stored in their user record in the database.

The user preference for preferred colour map has been given the name PREFERRED_COLOUR_MAP. This is configurable via the config file. The front end will need to give users the ability to set this preference.

The order of preference for which colour map to apply when returning images is as follows:

1. if a colourmap name is specified as one of the parameters of an API call then that is used
2. if no colourmap name is specified in the API call then the user's preference (if set) will be used
3. if neither of the above are set then the system default specified in the config file will be used

In addition to a new test for the get, set and delete functionality, the existing tests that return images have been modified to ensure that the correct images are returned when the user preference is set.

2023-09-04 14:18 UTC, MRichards99 requested changes
Implementation looks good, I couldn't break it and the test coverage is good. Just a couple of minor things I noticed while looking at the code

2023-09-06 10:11 UTC, louise-davies requested changes
Just testing what Matt deployed - and it's working fine expect that currently the `/colourbar` endpoint still returns the system default colourmap when a user has their preference set. We could in the frontend infer what the user set preferred colourmap is and send that parameter to the `/colourbar` endpoint, but I believe it should match the `/images` endpoint which does take the preferred colourmap into account.

2023-09-07 12:21 UTC, kevinphippsstfc commented
Thanks @louise-davies I think you are right and the colourbar endpoint should match the other endpoints that return images. I did consider it when I was doing the development but for some reason concluded that it didn't need to change. I'll get it fixed.

2023-10-24 15:25 UTC, kevinphippsstfc commented on operationsgateway_api/src/exceptions.py
> +class MissingAttributeError(ApiError):
As discussed, I chose the name to try to keep it more generic in the hope that it can be re-used rather than creating many very specific exceptions.

2023-10-24 15:26 UTC, kevinphippsstfc commented on util/og_api_postman_collection.json
> +							"raw": "{\n\t\"name\": \"my_pref\",\n\t\"value\": \"my_value\"\n}",
Fixed in 5a50e4305cd857101458421219d703dacd1e7464

2023-10-24 15:26 UTC, kevinphippsstfc commented on util/og_api_postman_collection.json
> +							"raw": "{\n\t\"name\": \"my_pref\",\n\t\"value\": \"my_value\"\n}",
Fixed in 5a50e4305cd857101458421219d703dacd1e7464

2023-10-24 15:26 UTC, kevinphippsstfc commented on util/og_api_postman_collection.json
> +								"string_pref"
Fixed in 5a50e4305cd857101458421219d703dacd1e7464

2023-10-24 15:28 UTC, kevinphippsstfc commented on operationsgateway_api/src/routes/records.py
> +        log.info("Preferred colour map after user prefs check is %s", colourmap_name)
Fixed in cd8d64c45937c83f7939cf495cb0e72358522cc4 and 8ed720b4f812f4d16daf8743c12735b524223272

2023-10-25 08:11 UTC, kevinphippsstfc commented on operationsgateway_api/src/users/preferences.py
> +        log.debug("user_prefs_dict: %s", user_record_with_prefs)
Fixed in 5f181daa79af05be3be376e6ef5f59da3ffa7450

2023-10-25 08:12 UTC, kevinphippsstfc commented on operationsgateway_api/src/users/preferences.py
> +        log.debug(type(value))
Fixed in 5f181daa79af05be3be376e6ef5f59da3ffa7450

2023-10-25 08:18 UTC, kevinphippsstfc commented on operationsgateway_api/src/users/preferences.py
> +            log.debug("No user pref value %s found for user %s", pref_name, username)
Fixed in 5f181daa79af05be3be376e6ef5f59da3ffa7450 and cfe7a8745eeafd8fba1fad2f96222fab39b481f2

2023-10-25 08:19 UTC, kevinphippsstfc commented on operationsgateway_api/src/users/preferences.py
> +            log.debug("No user prefs set for user %s", username)
Fixed in 5f181daa79af05be3be376e6ef5f59da3ffa7450 and cfe7a8745eeafd8fba1fad2f96222fab39b481f2

2023-10-30 09:04 UTC, MRichards99 approved these changes
Looks good, all suggested changes addressed and Louise's bug fixed

2023-10-30 09:38 UTC, merged